---
name: Kubrick
author: clau
category: Interfaces

tags: [color, colour, picker, hsl, rgb]
docs: http://tabqwerty.com/2010/07/01/colour-me-kubrick.html
demo: http://tabqwerty.com/2010/07/01/colour-me-kubrick.html
current: 0.1